# pince_proto - Generated protobuf types for the pince protocol.
#
# Generated from proto/agent.proto and proto/frontend.proto using protoc.
# Do not edit by hand — regenerate with: scripts/gen_proto.sh
from . import agent_pb2
from .agent_pb2 import (
    AgentMessage,
    SupervisorMessage,
    Ready,
    ToolCallRequest,
    ResponseChunk,
    ResponseDone,
    AgentError,
    Heartbeat,
    Init,
    AgentConfig,
    ToolSchema,
    UserMessage,
    ToolCallResult,
    ToolCallDenied,
    Cancel,
    Shutdown,
    RiskLevel,
)

from . import frontend_pb2
from .frontend_pb2 import (
    FrontendMessage,
    SupervisorFrontendMessage,
    Auth,
    AuthResult,
    SendMessage,
    ApprovalResponse,
    ApprovalDecision,
    ListAgents,
    SpawnAgent,
    KillAgent,
    AgentResponseChunk,
    AgentResponseDone,
    ToolCallEvent,
    ToolResultEvent,
    ApprovalRequest,
    AgentList,
    AgentInfo,
    AgentStatus,
    AgentStatusChange,
    FrontendError,
)

__all__ = [
    # agent types
    "agent_pb2",
    "AgentMessage",
    "SupervisorMessage",
    "Ready",
    "ToolCallRequest",
    "ResponseChunk",
    "ResponseDone",
    "AgentError",
    "Heartbeat",
    "Init",
    "AgentConfig",
    "ToolSchema",
    "UserMessage",
    "ToolCallResult",
    "ToolCallDenied",
    "Cancel",
    "Shutdown",
    "RiskLevel",
    # frontend types
    "frontend_pb2",
    "FrontendMessage",
    "SupervisorFrontendMessage",
    "Auth",
    "AuthResult",
    "SendMessage",
    "ApprovalResponse",
    "ApprovalDecision",
    "ListAgents",
    "SpawnAgent",
    "KillAgent",
    "AgentResponseChunk",
    "AgentResponseDone",
    "ToolCallEvent",
    "ToolResultEvent",
    "ApprovalRequest",
    "AgentList",
    "AgentInfo",
    "AgentStatus",
    "AgentStatusChange",
    "FrontendError",
]
